#include <stdio.h>
#include <unistd.h>

void recurse(int depth) {
    char buffer[4096]; // Allocate some stack space to speed up overflow
    // printf("Recursion depth: %d, stack addr: %p\n", depth, &buffer);
    recurse(depth + 1); // Recursive call
}

int main() {
    char cmd[64];
    sprintf(cmd, "cat /proc/%d/maps", getpid());
    system(cmd);
    recurse(1);
    return 0;
}

/*

604abba2e000-604abba2f000 r--p 00000000 103:02 262194                    /tmp/stack_overflow
604abba2f000-604abba30000 r-xp 00001000 103:02 262194                    /tmp/stack_overflow
604abba30000-604abba31000 r--p 00002000 103:02 262194                    /tmp/stack_overflow
604abba31000-604abba32000 r--p 00002000 103:02 262194                    /tmp/stack_overflow
604abba32000-604abba33000 rw-p 00003000 103:02 262194                    /tmp/stack_overflow
737846e00000-737846e28000 r--p 00000000 103:02 3157728                   /usr/lib/x86_64-linux-gnu/libc.so.6
737846e28000-737846fbd000 r-xp 00028000 103:02 3157728                   /usr/lib/x86_64-linux-gnu/libc.so.6
737846fbd000-737847015000 r--p 001bd000 103:02 3157728                   /usr/lib/x86_64-linux-gnu/libc.so.6
737847015000-737847016000 ---p 00215000 103:02 3157728                   /usr/lib/x86_64-linux-gnu/libc.so.6
737847016000-73784701a000 r--p 00215000 103:02 3157728                   /usr/lib/x86_64-linux-gnu/libc.so.6
73784701a000-73784701c000 rw-p 00219000 103:02 3157728                   /usr/lib/x86_64-linux-gnu/libc.so.6
73784701c000-737847029000 rw-p 00000000 00:00 0 
7378471d1000-7378471d4000 rw-p 00000000 00:00 0 
7378471ea000-7378471ec000 rw-p 00000000 00:00 0 
7378471ec000-7378471ee000 r--p 00000000 103:02 3157720                   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7378471ee000-737847218000 r-xp 00002000 103:02 3157720                   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
737847218000-737847223000 r--p 0002c000 103:02 3157720                   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
737847224000-737847226000 r--p 00037000 103:02 3157720                   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
737847226000-737847228000 rw-p 00039000 103:02 3157720                   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7ffe1f95c000-7ffe1f97d000 rw-p 00000000 00:00 0                          [stack]
7ffe1f9e8000-7ffe1f9ec000 r--p 00000000 00:00 0                          [vvar]
7ffe1f9ec000-7ffe1f9ee000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]
*/

/*
How to execute
1. gcc -o /tmp/stack_overflow stack_overflow.c
2. /tmp/stack_overflow

It will produce code dump

3. gdb /tmp/stack_overflow /tmp/core.stack_overflow.4479.1751362632
//------------------------------------------------------
Reading symbols from /tmp/stack_overflow...
[New LWP 5462]

warning: Section `.reg-xstate/5462' in core file too small.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/tmp/stack_overflow'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Section `.reg-xstate/5462' in core file too small.
#0  0x0000604abba2f1d8 in recurse (depth=<error reading variable: Cannot access memory at address 0x7ffe1f17ccec>)
    at /media/ssd/Project/Linux-learning/memory/stack_overflow.c:4

warning: Source file is more recent than executable.
4       void recurse(int depth) {
//------------------------------------------------------

4. info registers rsp # -> gives top of stack at the time of crash
rsp            0x7ffe1f17cd00      0x7ffe1f17cd00

5.check stack segment range in /tmp/op.txt
7ffe1f95c000-7ffe1f97d000 rw-p 00000000 00:00 0                          [stack]

Analysis:
- 0x7ffe1f17cd00 (rsp at crash) is less than 0x7ffe1f95c000 (stack segment start).
- This means the stack pointer has moved below the allocated stack region, into the guard page, causing a segmentation fault (stack overflow).
*/

